# Generated by Django 3.1.7 on 2021-03-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Train_No', models.CharField(max_length=100, null=True)),
                ('To', models.CharField(choices=[('Anna Nagar', 'Anna Nagar'), ('Alanthur', 'Alanthur'), ('Parrys Corner', 'Parrys Corner'), ('Porur', 'Porur'), ('Vadapalani', 'Vadapalani'), ('Koyembedu', 'Koyembedu')], max_length=100, null=True)),
                ('From', models.CharField(choices=[('Anna Nagar', 'Anna Nagar'), ('Alanthur', 'Alanthur'), ('Parrys Corner', 'Parrys Corner'), ('Porur', 'Porur'), ('Vadapalani', 'Vadapalani'), ('Koyembedu', 'Koyembedu')], max_length=100, null=True)),
                ('Train_fare', models.FloatField(null=True)),
                ('Train_Status', models.CharField(choices=[('Arriving...', 'Arriving...'), ('Departed Already', 'Departed Already'), ('Cancelled', 'Cancelled'), ('Late', 'Late')], max_length=100, null=True)),
                ('Time_of_arrival', models.TimeField()),
            ],
        ),
    ]
